# Generated by Django 4.1.6 on 2024-01-24 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donation_page", "0007_remove_donationpage_commision_percent_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamer",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Balance"
            ),
        ),
        migrations.AlterField(
            model_name="streamer",
            name="donation_page",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donation_page.donationpage",
                verbose_name="Donation page",
            ),
        ),
        migrations.AlterField(
            model_name="streamer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="streamer",
            name="profile_image_url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Profile image url"
            ),
        ),
    ]
