# Generated by Django 4.1.6 on 2023-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.IntegerField(verbose_name="Кількість"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.TextField(verbose_name="Повідомлення"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="nickname",
            field=models.CharField(max_length=128, verbose_name="Нікнейм"),
        ),
    ]
