# Generated by Django 4.1.6 on 2023-04-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Повідомлення"),
        ),
    ]
