# Generated by Django 4.1.6 on 2024-01-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_alter_donation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.IntegerField(verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="nickname",
            field=models.CharField(max_length=128, verbose_name="Nickname"),
        ),
    ]
