# Generated by Django 4.2.9 on 2024-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_alter_donation_amount_alter_donation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="shown",
            field=models.BooleanField(default=False, verbose_name="Shown"),
        ),
    ]
