# Generated by Django 4.1.6 on 2023-02-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="amount_max",
            field=models.IntegerField(default=10000, verbose_name="Максимальна сума"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="amount_min",
            field=models.IntegerField(default=1, verbose_name="Мінімальна сума"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="amount_placeholder",
            field=models.CharField(
                default="Сума", max_length=32, verbose_name="Плейсхолдер суми"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="commision_percent",
            field=models.FloatField(default=0.5, verbose_name="Комісія від суми"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="donate_button_text",
            field=models.CharField(
                default="Скинути Грошик",
                max_length=32,
                verbose_name="Текст кнопки подяки",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_max_length",
            field=models.IntegerField(
                default=333, verbose_name="Максимальна довжина повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_min_length",
            field=models.IntegerField(
                default=0, verbose_name="Мінімальна довжина повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_placeholder",
            field=models.CharField(
                default="Повідомлення",
                max_length=255,
                verbose_name="Плейсхолдер повідомлення",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_max_length",
            field=models.IntegerField(
                default=69, verbose_name="Максимальна довжина нікнейму"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_min_length",
            field=models.IntegerField(
                default=1, verbose_name="Мінімальна довжина нікнейму"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_placeholder",
            field=models.CharField(
                default="Нікнейм", max_length=64, verbose_name="Плейсхолдер нікнейму"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_link",
            field=models.CharField(
                max_length=255, verbose_name="Посилання на сторінку"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_meta",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Мета теги сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_title",
            field=models.CharField(
                default="Скинути Грошик",
                max_length=255,
                verbose_name="Заголовок сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="target_amount",
            field=models.IntegerField(default=10000, verbose_name="Сума цілі"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="target_title",
            field=models.CharField(
                default="Ціль. Зібрано {} грн",
                max_length=255,
                verbose_name="Заголовок цілі",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="test_mode",
            field=models.BooleanField(default=False, verbose_name="Тестовий режим"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="title",
            field=models.CharField(
                default="Скинути Грошик Стрімеру",
                max_length=255,
                verbose_name="Заголовок привітання",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="title_subtext",
            field=models.CharField(
                default="Скинь Грошик цьому стрімеру",
                max_length=255,
                verbose_name="Підзаголовок привітання",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="viewer_pays_commision",
            field=models.BooleanField(
                default=True, verbose_name="Глядач платить комісію"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="widgets",
            field=models.ManyToManyField(
                related_name="donation_pages",
                to="donation_page.widget",
                verbose_name="Віджети",
            ),
        ),
    ]
