# Generated by Django 4.1.6 on 2023-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_page", "0003_donationpage_target_current_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="target_title",
            field=models.CharField(
                default="На хаймарс", max_length=255, verbose_name="Заголовок цілі"
            ),
        ),
    ]
