# Generated by Django 4.1.6 on 2023-06-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation_page", "0004_alter_donationpage_target_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="widgets",
        ),
        migrations.DeleteModel(
            name="Widget",
        ),
    ]
