# Generated by Django 4.1.6 on 2023-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_page", "0005_remove_donationpage_widgets_delete_widget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="page_link",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Посилання на сторінку"
            ),
        ),
    ]
