# Generated by Django 4.1.6 on 2024-01-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donation_page", "0006_alter_donationpage_page_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="commision_percent",
        ),
        migrations.RemoveField(
            model_name="donationpage",
            name="viewer_pays_commision",
        ),
        migrations.AddField(
            model_name="donationpage",
            name="commission_percent",
            field=models.FloatField(default=0.5, verbose_name="Commission percent"),
        ),
        migrations.AddField(
            model_name="donationpage",
            name="viewer_pays_commission",
            field=models.BooleanField(
                default=True, verbose_name="Viewer pays a commission"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="amount_max",
            field=models.IntegerField(default=10000, verbose_name="Maximum amount"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="amount_min",
            field=models.IntegerField(default=1, verbose_name="Minimum amount"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="amount_placeholder",
            field=models.CharField(
                default="Amount", max_length=32, verbose_name="Amount placeholder"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="donate_button_text",
            field=models.CharField(
                default="Send Hroshyk",
                max_length=32,
                verbose_name="Donation button text",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_max_length",
            field=models.IntegerField(
                default=333, verbose_name="Maximum message length"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_min_length",
            field=models.IntegerField(default=0, verbose_name="Minimum message length"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="message_placeholder",
            field=models.CharField(
                default="Message", max_length=255, verbose_name="Message placeholder"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_max_length",
            field=models.IntegerField(
                default=69, verbose_name="Maximum nickname length"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_min_length",
            field=models.IntegerField(
                default=1, verbose_name="Minimum nickname length"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="nickname_placeholder",
            field=models.CharField(
                default="Nickname", max_length=64, verbose_name="Nickname placeholder"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_link",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Page link"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_meta",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Page meta description",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="page_title",
            field=models.CharField(
                default="Send Hroshyk", max_length=255, verbose_name="Page title"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="target_amount",
            field=models.IntegerField(
                default=10000, verbose_name="Donation target amount"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="target_current_amount",
            field=models.IntegerField(
                default=0, verbose_name="Donation target current amount"
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="target_title",
            field=models.CharField(
                default="Donation target",
                max_length=255,
                verbose_name="Donation target title",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="test_mode",
            field=models.BooleanField(default=False, verbose_name="Test mode"),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="title",
            field=models.CharField(
                default="Send Hroshyk to the streamer",
                max_length=255,
                verbose_name="Greeting title",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="title_subtext",
            field=models.CharField(
                default="Send Hroshyk to this streamer",
                max_length=255,
                verbose_name="Greeting subtext",
            ),
        ),
    ]
