# Generated by Django 4.1.6 on 2023-06-17 18:21

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import widgets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва віджета"),
                ),
                (
                    "link_identifier",
                    models.CharField(
                        default=widgets.models.generate_link_identifier,
                        max_length=128,
                        unique=True,
                        verbose_name="Посилання на віджет",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата створення"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DonationWidgetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_format",
                    models.CharField(
                        default="{nickname} - {amount}",
                        max_length=255,
                        verbose_name="Формат заголовку",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(default=20, verbose_name="Мінімальна сума для відображення"),
                ),
                (
                    "max_amount",
                    models.IntegerField(default=10000, verbose_name="Максимальна сума для відображення"),
                ),
                (
                    "title_font_size",
                    models.IntegerField(default=24, verbose_name="Розмір шрифту заголовку"),
                ),
                (
                    "title_color",
                    models.CharField(default="#ffffff", max_length=7, verbose_name="Колір заголовку"),
                ),
                (
                    "title_shadow_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Колір тіні заголовку",
                    ),
                ),
                (
                    "message_font_size",
                    models.IntegerField(default=20, verbose_name="Розмір шрифту повідомлення"),
                ),
                (
                    "message_color",
                    models.CharField(
                        default="#ffffff",
                        max_length=7,
                        verbose_name="Колір повідомлення",
                    ),
                ),
                (
                    "message_shadow_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Колір тіні повідомлення",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="donation_widget/images/", verbose_name="Зображення"),
                ),
                (
                    "sound",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="donation_widget/sounds/",
                        verbose_name="Мелодія",
                    ),
                ),
                (
                    "sound_volume",
                    models.IntegerField(default=100, verbose_name="Гучність мелодії"),
                ),
                (
                    "speaker_volume",
                    models.IntegerField(default=100, verbose_name="Гучність спікера"),
                ),
                (
                    "donation_widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="widgets.donationwidget",
                    ),
                ),
            ],
        ),
    ]
